-- MySQL Script generated by MySQL Workbench
-- 07/08/18 23:14:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema servidor_rest_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema servidor_rest_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `servidor_rest_test` DEFAULT CHARACTER SET utf8 ;
USE `servidor_rest_test` ;

-- -----------------------------------------------------
-- Table `servidor_rest_test`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servidor_rest_test`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(64) NOT NULL,
  `nombre` VARCHAR(128) NOT NULL,
  `apellido_paterno` VARCHAR(64) NOT NULL,
  `apellido_materno` VARCHAR(64) NOT NULL,
  `tiempo_registro` TIMESTAMP NOT NULL,
  `tiempo_edicion` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `servidor_rest_test`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servidor_rest_test`.`empresa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(128) NOT NULL,
  `tiempo_registro` TIMESTAMP NOT NULL,
  `tiempo_edicion` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `servidor_rest_test`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servidor_rest_test`.`proyecto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `id_empresa` INT NOT NULL,
  `nombre` VARCHAR(128) NOT NULL,
  `precio` DOUBLE NOT NULL,
  `tiempo_registro` TIMESTAMP NOT NULL,
  `tiempo_edicion` TIMESTAMP NOT NULL,
  INDEX `id_cliente_idx` (`id_cliente` ASC),
  INDEX `id_empresa_idx` (`id_empresa` ASC),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `id_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `servidor_rest_test`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `servidor_rest_test`.`empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
